### ISSUE TITLE
Consider refactoring `isIn` to `isTaggedWith`

### ISSUE THREAD

**Issue by supersaiyansubtlety** [QuiltMC/quilt-mappings#113]
`isTaggedWith` is more in line with conventional "tag" terminology. 

Prior to 1.18.2 tags could be reasonably treated as sets of the things they tag because of `Tag::contains`. Post-1.18.2, however, Mojang's removal of this indicates to me that they're doubling down on tags as conventional "tags", similar to those used to organize files or even hashtags on social media: the focus is on what tags a single thing is tagged with, rather than which things are tagged with a single tag. 

I think `isIn` will make devs waste time looking for `contains` methods only to be surprised when they ask and find they don't exist.

**Comment by eristhea** [comment]
As the person that [tried to rename `isIn` to `hasTag`](https://github.com/QuiltMC/quilt-mappings/pull/236), I think this just the same thing as that, and it's been decided against. This issue can probably be closed after that discussion
