### ISSUE TITLE
Relocating some classes to com/mojang/blaze3d

### ISSUE THREAD

**Issue by OroArmor** [QuiltMC/quilt-mappings#12]
Should classes in `com/mojang/blaze3d` that are obfuscated be moved to that package now that we can reference mojmap. This would mostly affect rendering, but it would help seperate out the rendering engine from the rest of the game. This would help modders know what makes up the underlying api versus the actual minecraft API.

This could also be extended to realms, making that code more easily distinguishable

**Comment by OroArmor** [comment]
Example `net/minecraft/client/gl/GlUniform -> com/mojang/blaze3d/shaders/Uniform`. This is qm to mojmap. This issue does not say to rename any classes. it just suggests that `GlUniform` should be placed in a subpackage of `com/mojang/blaze3d` not `net/minecraft`

**Comment by TropheusJ** [comment]
I don't see why not, it would make sense. And IIRC mojang said they wanted to split off Blaze3d and open source it at some point, so this change would be needed later down the line anyway. However package structure and naming would still be different, so I'm not sure if this would actually be too beneficial for that.

**Comment by AlsoSylv** [comment]
Where mappings are should probably match mojmap, unless of course it is widely off of the actual use, but in this case it doesn't seem to be.

**Comment by IotaBread** [comment]
I don't see any reason not to do it

**Comment by OroArmor** [comment]
Alright, @LambdAurora any thoughts on this? I think you had some in discord, but I don't remember them.

**Comment by LambdAurora** [comment]
I said I'm fine as long as it's truly Blaze3D stuff and not MC internals ;)

**Comment by OroArmor** [comment]
alright then, I will update my PR when i have a chance. i will close this when that pr is merged
