### ISSUE TITLE
`Screen.onClose` is misleading

### ISSUE THREAD

**Issue by Juuxel** [QuiltMC/quilt-mappings#161]
It closes the screen by calling `client.setScreen(null)`, so it's not an "listener" for closing screens like the name would suggest.

**Comment by triphora** [comment]
This is `Screen.close` in Yarn, but if I recall correctly that caused some naming conflicts for me when trying to add another mod to my dev env, so my only option to get that mod in my dev env was to switch to QM where it wasn't `close`
