### ISSUE TITLE
Documentation discussion for `MatrixStack`

### ISSUE THREAD

**Issue by i509VCB** [QuiltMC/quilt-mappings#203]
I have recently been playing around with implementing a scene graph in Rust. Although that is unrelated to quilt-mappings, it did give me some more insight into `MatrixStack` and how it works:

In a very literal sense, a `MatrixStack` is a stack of matrices. You `push` and `pop` frames into a stack. You can then apply transforms to the current head of the stack. Draw calls get passed the current matrix stack and get a `Matrix4f` (or whatever it's called, it's a 4x4 matrix). So it would seem logical to name the type `MatrixStack`.

A `MatrixStack` at it's core is really a "transform stack". The matrices you insert into the `MatrixStack` describe a transform (scale, rotation, translation). OpenGL uses the resulting 4x4 matrix to transform the vertices when rendering.

Now wait, how did Mojang come up with `PoseStack` per the `toString` implementation? I'm not sure to be fair. Maybe it was related to positioning parts of an entity initially. But in actuality the entire world is transformed using the matrix stack.

**Comment by FoundationGames** [comment]
Older versions of OpenGL had a built-in matrix stack, and they called it that too, which is a likely explanation for MatrixStack's name

"Pose stack" is likely a name chosen by mojang to describe MatrixStack's functionality very simply - you can push and modify the "pose" of whatever you're rendering (hence the convenience methods specifically for translation and rotation, albeit scaling is present too)

Do note that MatrixStack's entries also contain a 3x3 normal transform matrix as well, and that could be a reason for mojang's very general choice of "pose stack"

If it were me writing a game engine, I would call it TransformStack or just Transforms, but I think the current yarn/quiltmap name is good enough

**Comment by eristhea** [comment]
why settle for good enough? `TransformStack` seems like a much more accurate name.

**Comment by eristhea** [comment]
following a [chat on discord](https://discord.com/channels/833872081585700874/877319390901706753/1099386435754262669), we've determined that the `TransformStack` name is better, but the refactor is simply too big to undertake to improve a name that's already fairly good.
