### ISSUE TITLE
Rename ScoreHolderArgumentType.getScoreboardScoreHolders

### ISSUE THREAD

**Issue by Cypher121** [QuiltMC/quilt-mappings#205]
The difference between getScoreHolders and this is that it returns all players if given a `*` wildcard instead of throwing an exception.

Mojmap's getNamesWithDefaultWildcard is closer to the truth, though still not ideal: "default" is actually "all known players" here.

**Comment by ghost** [comment]
Maybe something like getAnyPlayer, since it gets anything.
