### ISSUE TITLE
getModel -> getPosition rename was a mistake

### ISSUE THREAD

**Issue by LambdAurora** [QuiltMC/quilt-mappings#216]
So, I don't have the class in mind but y'all we see what I mean with this code excerpt:

```java
MatrixStack matrices;

/* code */

matrices.peek().getModel()
```

`getModel` was renamed to `getPosition` during the big rendering refactor, we imported lot of mojmap names woooo so we finally have stuff be accurate.

Except this name.
No it's not a position, it's a model matrix.
"wdym it's not a position?"

It contains **both** a translation and a rotation of the model.
It's not just a position it's more.

If we want to be the most accurate possible it should be `getModelMatrix` but that's a tad long. And given where it's used in the code, it's a bit useless since, well, we already usually know that it's a matrix.

The question though is, should this rename happen once again?
This would fuel the possible complaints of QM being unstable, but it's also very bothering to me to keep this name.
So please voice your opinion below!

**Comment by supersaiyansubtlety** [comment]
I don't think fear of being called unstable should prevent us from fixing a mistake.
