### ISSUE TITLE
Rename `ScreenHandler.transferSlot(index)`

### ISSUE THREAD

**Issue by FoundationGames** [QuiltMC/quilt-mappings#222]
The method's name isn't very good at describing what it does specifically - it's the method which handles shift clicking a slot and quick transferring the item to whatever slot is appropriate

Both the method and the parameter should be renamed to something like `quickTransfer(originalSlotId)`

**Comment by babedipaai** [comment]
How about transferItem(appropriateSlot)

**Comment by Jamalam360** [comment]
transferItem doesn't convey that it's for quick transfering really

**Comment by OroArmor** [comment]
The main point of this issue is that `transfer` doesn't currently describe the method properly, where `quick` is the needed information. I would even say that `transferItem` is the same as `transferSlot` since they both give the same information when reading the name.

**Comment by Jamalam360** [comment]
I'd also like to bring some related methods that I was confused with last night to attention. Item#onClicked, and Item#onStackClicked. BundleItem implements both so that's a good example of what's going on. These might benefit from javadoc rather than a rename though, I'll look into it further

**Comment by Jamalam360** [comment]
Am claiming this (ooo i have powers to assign myself)

**Comment by Jamalam360** [comment]
`quickTransfer` has been born :)
