### ISSUE TITLE
`drawTexture` has incorrect parameter names

### ISSUE THREAD

**Issue by floppydiskette** [QuiltMC/quilt-mappings#233]
the last two parameters of the exposed `drawTexture` function, that being `textureHeight` and `textureWidth`, seem to actually be opposites of each other (`textureHeight` controls width, `textureWidth` controls height).  
  
the following code generates a correctly scaled texture (note the "incorrect" parameters provided)
![](https://imgur.com/GFTWqnD.png)
however, the following code generates an incorrectly scaled texture (note the "correct" parameters provided)
![](https://imgur.com/Aeh9QxE.png)

**Comment by ghost** [comment]
Where is this method?

**Comment by floppydiskette** [comment]
`net.minecraft.client.gui.DrawableHelper`
