### ISSUE TITLE
Intermediary QM has issues.......

### ISSUE THREAD

**Issue by maximumpower55** [QuiltMC/quilt-mappings#257]
There isn't really one clear issue with Intermediary QM but I will list some of the issues that happen when using it with Quilt Loom

### Unmapped classes, methods, fields, etc are still in hashed mojmap even in Intermediary QM!
- Some classes are randomly unmapped in decompiled MC sources
- Layered mappings are basically broken, Quilt Loom just fails to remap MC sometimes when layering Intermediary QM with other mappings (Mojmap, Mojmap + Parchment, etc)

### Issues that don't have a clear source but are caused by Intermediary QM
- When using external deps in a Quilt Loom Project, Quilt Loader fails to find them resulting in the game not being able to launch

I will be extending this list as I find more issues with Intermediary QM

**Comment by maximumpower55** [comment]
Extra Info: these issues did not happen when using QM through the quilt mappings on loom gradle plugin

**Comment by eristhea** [comment]
related to #304, could you please remove the first half of this issue in favour of that one?

**Comment by maximumpower55** [comment]
> related to #304, could you please remove the first half of this issue in favour of that one?

I don't see why I should since my issue was created before that one, tho that issue does provide a little bit more info than mine

**Comment by eristhea** [comment]
having one report for every individual issue is preferred, and it's just simpler to devote this report to your second issue and let #304 cover the first
