### ISSUE TITLE
Some enum mappings in NativeImage are wrong

### ISSUE THREAD

**Issue by Jamalam360** [QuiltMC/quilt-mappings#29]
If I'm not mistaken, the name of `NativeImage.Format.ABGR` should probably be changed to `NativeImage.Format.RGBA`.

Source 1:
```java
public int getPixelColor(int x, int y) {
        if (this.format != NativeImage.Format.ABGR) {
            throw new IllegalArgumentException(String.format("getPixelRGBA only works on RGBA images; have %s", this.format));
        } else [...]
 }
 ```
 
 The enum name is different to the name given in the error message
 
 Source 2:

![image](https://user-images.githubusercontent.com/56727311/140619439-58d7c587-f625-4cf4-ac27-c5143c53da54.png)

The offsets of the colour values show they're in the order RGBA

The issue also seems to affect `NativeImage.Format.BGR`, although I haven't tested that specific one, the offset values also show it should probably be `RGB`

**Comment by Jamalam360** [comment]
Apologies, this was fixed in yarn https://github.com/FabricMC/yarn/commit/64b428097f66c928c156f38cff40360829b416c9

Edit: Now I look at it, the error is still here in QM

**Comment by i509VCB** [comment]
I've seen this before, it is little endian, hence the `BGR` ordering instead of `RGB`

**Comment by skyrising** [comment]
Mojang calls it `ARGB` and `RGB` so that's what the string constants in the bytecode say. Not sure if there's conventions on this, but I don't think we should call enums anything different from their canonical name.
