### ISSUE TITLE
`C_cifoaixd$C_lcybgaxw$C_amqftyfx$C_iinezlaz` is broken

### ISSUE THREAD

**Issue by LudoCrypt** [QuiltMC/quilt-mappings#334]
Its in ChunkBuilder.BuiltChunk.RebuildTask. I found it by that class' render method, its return value is that class `C_cifoaixd$C_lcybgaxw$C_amqftyfx$C_iinezlaz` and it is very broken. It wont let me import it. `C_cifoaixd$C_lcybgaxw$C_amqftyfx` (the first part of it) just maps to `ChunkBuilder.BuiltChunk.RebuildTask`. I dont know what else to put here.

**Comment by IotaBread** [comment]
Could you provide a bit more information? Like how are you decompiling, which QM version this is, or some screenshots

**Comment by LudoCrypt** [comment]
The issue is right here https://github.com/QuiltMC/quilt-mappings/blob/1.19.3/mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping#L121

All my settings are from the Quilt Template mod. I dont think its an issue on my side. It should be a simple fix, just change the thing. Idk tho I've never done mappings before.

**Comment by LudoCrypt** [comment]
This is what the method looks like to me
![Screenshot_94](https://user-images.githubusercontent.com/60561627/211207102-06167769-b956-4960-8193-57ebc1d03bac.png)
I cannot ctrl click to open it up.
IntelliJ has a feature where you can search anywhere in a project, so I did just that.

This class is what shows up.
![Screenshot_95](https://user-images.githubusercontent.com/60561627/211207147-18040968-dd83-4adb-b516-8a87ba3d46b9.png)

Yet I search in the very folder that its from and theres nothing of it!
![Screenshot_96](https://user-images.githubusercontent.com/60561627/211207176-969895e6-d49b-4858-a653-cf564f1ebccc.png)
I looked in the sources-jar manually and found it.

Eclipse? Same story. Cant click it to open it. Cannot find it. and of course, cannot import it even when using an access widener which does work.

As the first part technically maps to `ChunkBuilder.BuiltChunk.RebuildTask` I thought maybe its hidden in there? But there's nothing to be found.

Tried to open up the bytecode but it says its unable to parse.

I am using `quilt_mappings = "1.19.3+build.16"`, `quilt_loader = "0.17.8"`, `quilt_loom = { id = "org.quiltmc.loom", version = "1.0.+" }`, `mappings "org.quiltmc:quilt-mappings:${libs.versions.quilt.mappings.get()}:intermediary-v2"`
I don't know what other information is necessary.

**Comment by IotaBread** [comment]
Hm, this is quite the issue. We'll have to invesigate

**Comment by mmodrow** [comment]
#371 explicitly said "Doesn't fix #334 yet", which was bad phrasing. I guess this was closed by accident.

**Comment by eristhea** [comment]
this actually did fix the inner class issues, see this comment!
https://github.com/QuiltMC/quilt-mappings/pull/371#issuecomment-1457001078

**Comment by mmodrow** [comment]
> this actually did fix the inner class issues, see this comment!
> 
> https://github.com/QuiltMC/quilt-mappings/pull/371#issuecomment-1457001078

Thanks for the clarification. I didn't have the domain knowledge to catch that. I'm just subscribed, because a mc mod dev I'm waiting to update their work depends on this fix and I wanted to stay in the loop XD.
