### ISSUE TITLE
Record fields not decompiled correctly

### ISSUE THREAD

**Issue by jschenke488** [QuiltMC/quilt-mappings#381]
When running `decompileQuiltflower`, fields in records are duplicated like this. In this case, locations is duplicated.
<img width="945" alt="image" src="https://user-images.githubusercontent.com/44783760/222574396-1ef6cbf4-3ae0-4b16-8e4f-6f892da95a42.png">

**Comment by jschenke488** [comment]
The same thing happens with `mapNamedJar` and running Quiltflower manually.

**Comment by OroArmor** [comment]
From the README.md:
> **Note:** This is not designed to be recompiled.

While this may be annoying, it is not the goal of Quilt Mappings to produce recompilable code.

**Comment by jaskarth** [comment]
For what it's worth, this has since been fixed on Quiltflower's side.
