### ISSUE TITLE
`AbstractRedstoneGateBlock$isValidInput` is ambiguous

### ISSUE THREAD

**Issue by Oliver-makes-code** [QuiltMC/quilt-mappings#434]
The method `AbstractRedstoneGateBlock$isValidInput(BlockState state)` is ambiguous. It doesn't let the reader know that it checks the sides of the block, not the actual block itself, and it also doesn't let the reader know that it doesn't check in front/back of the block. A better name would be `isSideInputValid`

**Comment by SpaceWalkerRS** [comment]
iirc that method was removed in a recent snapshot so this only concerns 1.19.4 and below. If this issue is fixed though maybe we should consider back porting #402 as well.
