### ISSUE TITLE
`velocityXYZ` names are violating conventions

### ISSUE THREAD

**Issue by eristhea** [QuiltMC/quilt-mappings#459]
as discussed in [this pr](https://github.com/QuiltMC/quilt-mappings/pull/458#pullrequestreview-1509628359) and [on discord](https://discord.com/channels/817576132726620200/1104011466660659273/1125106985168277534), `velocityXYZ` reads much less naturally than `xyzVelocity`, which means that `velocityXYZ` names are in violation of the conventions, specifically this section of "[general](https://github.com/QuiltMC/quilt-mappings/blob/1.20.1/CONVENTIONS.md#general)":
> To make code as easy to read as possible, keep names in the natural language order. For example, a class representing a chest block entity should be named ChestBlockEntity rather than BlockEntityChest. Though prefix naming may be helpful for grouping classes together in an IDE's tree view, reading and writing code is done much more often than browsing files.

**Comment by eristhea** [comment]
additionally, seeing how common this mistake is, we should add this as an example in the conventions.

**Comment by supersaiyansubtlety** [comment]
Re-posting what I [said on discord](https://discord.com/channels/817576132726620200/1104011466660659273/1125275349249425438):
> iiuc its
"velocity's x component" for `velocityX`
vs
"x component of velocity" for `xVelocity`
imo both are pretty natural, so no reason to change it

Additionally, this would contradict the [Coordinates](https://github.com/QuiltMC/quilt-mappings/blob/1.20.1/CONVENTIONS.md#coordinates) convention, which goes so far as to specify "velocityX, not xVelocity"
> Coordinates can be named x, y, and z when it's clear what they represent. If clarification is needed, add a word in front of the coordinate (velocityX, not xVelocity).

When this was brought up on discord it seemed like there was a distinct lack of agreement that the current "velocityX" order is less natural.

There was also disagreement on the current "velocityX" being less natural in #458 where, to my knowledge, this discussion started. [Start of discussion](https://github.com/QuiltMC/quilt-mappings/pull/458#pullrequestreview-1509628359).

**Comment by Antikyth** [comment]
I agree with @supersaiyansubtlety that `velocityXYZ` is a better word order.  However, does it make more sense for it to be `velocityXyz`?  I think probably not, it just depends on whether you want to treat it like an acronym (which it isn't) or not:
> Treat acronyms as single words rather than capitalizing every letter. This improves readability (compare `JsonObject` and `JSONObject`) and it's consistent with Mojang naming (a known name is `NbtIo`).

**Comment by supersaiyansubtlety** [comment]
The issue is actually about `velocityX`, `velocityY`, and `velocityZ`.
`velocityXYZ` is just shorthand to talk about all 3.

**Comment by eristhea** [comment]
I'm not sure I support this change anymore, but if anyone has another argument for it I'd love to hear it. otherwise, I'm closing the issue.
