### ISSUE TITLE
int sequence fields are not sequences

### ISSUE THREAD

**Issue by supersaiyansubtlety** [QuiltMC/quilt-mappings#470]
discussed here: https://github.com/QuiltMC/quilt-mappings/pull/469#discussion_r1275701457

Some relevant fields:

`ServerPlayNetworkHandler#blockChangeSequence`
`PlayerInteractionWithItemC2SPacket#sequence`
`PlayerActionC2SPacket#sequence`
`PlayerInteractionWithBlockC2SPacket#sequence`
`BlockUpdateAcknowledgmentS2CPacket#sequence`

These integers aren't sequences. AFAICT, they indicate their instance's order within a sequence.

What I found:
These `sequence` fields either default to 0 or their value traces back to `C_czisrdmd#field_37954`.
This field is incremented in `C_czisrdmd#method_41937`, which is only called by `ClientPlayerInteractionManager#method_41931`.
`method_41931` is passed packet factories that take an `int` (`C_czisrdmd#field_37954`) and create the above packets with that sequence.

I think `sequenceIndex` would be a better name.

**Comment by eristhea** [comment]
more names affected by this issue are being added in #471, if you'd like to fix it please wait until that's merged!
