### ISSUE TITLE
`AbstractClientPlayerEntity#getSpeed` is poorly named

### ISSUE THREAD

**Issue by OroArmor** [QuiltMC/quilt-mappings#484]
It has to do with FOV modification, and mojmap is `getFieldOfViewModifier`. Can 100% have a better name.

**Comment by mdfarhananwar** [comment]
I want to work on this. Can you assign me this task?

**Comment by eristhea** [comment]
don't worry about it; just make a pr and it'll be linked here when open

I like the moj name but we should double check that it's a modifier and not a multiplier
