### ISSUE TITLE
Error when joining or creating singleplayer world: "Client disconnected with reason: Failed to synchronize client with the server!"

### ISSUE THREAD

**Issue by fugleigh** [QuiltMC/quilt-mappings#564]
Sorry if this is the wrong place but i'm so confused and nowhere on google has anything helpful. I'm thinking it's a quilt problem but it's hard to be sure. When a world is done loading or creating (100%) it shows "mismatched entries for state of minecraft:block" and brings me to the multiplayer server screen (?)

[latest.log](https://github.com/QuiltMC/quilt-mappings/files/14619845/latest.log)

I had it briefly fixed after removing Bedrockify so I put like 5 other mods back in (since they must not have been causing the problem) and it hasn't worked since then even after re-removing those mods. So it's exactly as it was when it did work. It doesn't help to delete the config folder or any other tricks. This is really weird for singleplayer and idk what exactly I should do to fix it

**Comment by pyrox0** [comment]
Quilt Mappings isn't the place to file issues like this, as it's more of a mod-dev-focused part of quilt. I suggest you join [the Discord](https://discord.quiltmc.org) and ask in the #quilt-basic-support or #quilt-player-support channels, as helpers will be able to better help you there!

**Comment by JPeisach** [comment]
This should actually be moved to QFAPI probably. You can see a thread I made on a mod I'm making causing this issue. And it is, very, very annoying.
<img width="909" alt="Screenshot 2024-03-16 at 4 51 43 PM" src="https://github.com/QuiltMC/quilt-mappings/assets/24401303/1f3ec913-8d5d-44b7-9a2b-8e3b9316b847">
^ this was a rare occurrence, so a GUI ive never seen before
