### ISSUE TITLE
Renaming `ThreadedAnvilChunkStorage`

### ISSUE THREAD

**Issue by Leo40Git** [QuiltMC/quilt-mappings#6]
I have 2 problems with TACS' current name:
1. _`Anvil`_ - this class does not deal with the Anvil chunk format at all! That's handled by `ChunkSerializer`.
2. _`Storage`_ - this class is actually a chunk _manager_, not just storage!

Additionally, there's the field that stores an instance of TACS in `ServerChunkManager`. You'll never guess what it's called... and `ServerChunkManager` delegates most of its actions to this instance (see my 2nd point)!

Therefore, I propose:
- We rename `ThreadedAnvilChunkStorage` to `ThreadedChunkManager`.
- We also rename `ServerChunkManager.threadedAnvilChunkStorage` to `ServerChunkManager.delegate`.

**Comment by eristhea** [comment]
is there any reason no one has ever made another pr for this change?

**Comment by Leo40Git** [comment]
beyond me being too lazy, no
