### ISSUE TITLE
`Block::getRaycastShape` is a bad name

### ISSUE THREAD

**Issue by Kroppeb** [QuiltMC/quilt-mappings#64]

**Comment by eristhea** [comment]
can you elaborate on the issues with the name?

**Comment by Kroppeb** [comment]
I have a vague memory of this. I think it is the shape that is used for example for hoppers to represent the region it can suck up items?

**Comment by eristhea** [comment]
no?
I looked into it and this is used, for example, by the raycast that checks what block the player is looking at

**Comment by Gaming32** [comment]
There's more than one shape for that though. There's three different shapes used for raycasting. At least on 1.19.2.
