### ISSUE TITLE
Inconsistent update packets and handler methods

### ISSUE THREAD

**Issue by IotaBread** [QuiltMC/quilt-mappings#65]
There are some inconsistent method and packet names, for example `UpdateSignC2SPacket` vs `BookUpdateC2SPacket`, or `ServerPlayPacketListener#onJigsawUpdate` vs `ServerPlayPacketListener#onUpdateBeacon`.

I'd say we should use 'update' as prefix (`UpdateSomethingC2SPacket`) as opposed to using it as suffix (`SomethingUpdateC2SPacket`), and the handler method should be 'on packet name' (`onUpdateSomething`)

**Comment by eristhea** [comment]
should we consider moving *all* verb suffixes?
when I was looking at <https://github.com/QuiltMC/quilt-mappings/pull/66/files#diff-073f7777d975061549d1a94e51fc0ba848a15f69c7e5c68bd565991f308acca3R49>, I noticed that we have a method called `onNbtQuery`. If it was `onNbtUpdate` instead, we'd be changing it to `onUpdateNbt`, which makes me think that we should do the same with things like `query`.

I think a convention should be established for this.

**Comment by eristhea** [comment]
currently working on this.
a lot of packet names are very questionable, so this will be a massive refactor.
the plan is to establish a convention stating:

### Network Packets

Always suffix packet names with S2CPacket (server to client) or C2SPacket (client to server).

Packet names should be in the form of `NounVerbed`: `ResourcePackSentS2CPacket`, `BlockUpdatedS2CPacket`, `PlayerMovedC2SPacket`, etc.
