### ISSUE TITLE
Fix record naming in Enigma

### ISSUE THREAD

**Issue by IotaBread** [QuiltMC/quilt-mappings#67]
Currently, records aren't decompiled correctly and Enigma doesn't treat them properly. Enigma and decompilers expect a field and a method with the same name, but due to hashed mojmap, this isn't possible.

A possible solution to this would be to add a task in the mapping of the hashed jar to cross reference mojmap or hashed mojmap to pair them again by giving them the same name. This wouldn't have any effect in the final product, but would ease mapping records

**Comment by OroArmor** [comment]
I believe this is fixed
